package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AccountData generated by hbm2java
 */
@Entity
@Table(name="Account_Data"
    ,catalog="corebanking_db"
)
public class AccountData  implements java.io.Serializable {


     private Integer id;
     private Integer accountId;
     private String self;
     private String totalPages;

    public AccountData() {
    }

    public AccountData(Integer accountId, String self, String totalPages) {
       this.accountId = accountId;
       this.self = self;
       this.totalPages = totalPages;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="account_id")
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    
    @Column(name="self")
    public String getSelf() {
        return this.self;
    }
    
    public void setSelf(String self) {
        this.self = self;
    }
    
    @Column(name="total_pages")
    public String getTotalPages() {
        return this.totalPages;
    }
    
    public void setTotalPages(String totalPages) {
        this.totalPages = totalPages;
    }




}


