package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BalanceData generated by hbm2java
 */
@Entity
@Table(name="Balance_Data"
    ,catalog="corebanking_db"
)
public class BalanceData  implements java.io.Serializable {


     private Integer id;
     private Integer balanceId;
     private String self;
     private String totalPages;

    public BalanceData() {
    }

    public BalanceData(Integer balanceId, String self, String totalPages) {
       this.balanceId = balanceId;
       this.self = self;
       this.totalPages = totalPages;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="balance_id")
    public Integer getBalanceId() {
        return this.balanceId;
    }
    
    public void setBalanceId(Integer balanceId) {
        this.balanceId = balanceId;
    }
    
    @Column(name="self")
    public String getSelf() {
        return this.self;
    }
    
    public void setSelf(String self) {
        this.self = self;
    }
    
    @Column(name="total_pages")
    public String getTotalPages() {
        return this.totalPages;
    }
    
    public void setTotalPages(String totalPages) {
        this.totalPages = totalPages;
    }




}


