package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Balance generated by hbm2java
 */
@Entity
@Table(name="Balance"
    ,catalog="corebanking_db"
)
public class Balance  implements java.io.Serializable {


     private Integer id;
     private String accountId;
     private String amount;
     private String creditDebitIndicator;
     private String currency;
     private String dateTime;
     private String type;

    public Balance() {
    }

    public Balance(String accountId, String amount, String creditDebitIndicator, String currency, String dateTime, String type) {
       this.accountId = accountId;
       this.amount = amount;
       this.creditDebitIndicator = creditDebitIndicator;
       this.currency = currency;
       this.dateTime = dateTime;
       this.type = type;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="account_id")
    public String getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }
    
    @Column(name="amount")
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    
    @Column(name="credit_debit_indicator")
    public String getCreditDebitIndicator() {
        return this.creditDebitIndicator;
    }
    
    public void setCreditDebitIndicator(String creditDebitIndicator) {
        this.creditDebitIndicator = creditDebitIndicator;
    }
    
    @Column(name="currency")
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    
    @Column(name="date_time")
    public String getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }
    
    @Column(name="type")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


