package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CountrySubDivision generated by hbm2java
 */
@Entity
@Table(name="CountrySubDivision"
    ,catalog="corebanking_db"
)
public class CountrySubDivision  implements java.io.Serializable {


     private Integer id;
     private Integer deliveryAddressId;
     private String value;

    public CountrySubDivision() {
    }

    public CountrySubDivision(Integer deliveryAddressId, String value) {
       this.deliveryAddressId = deliveryAddressId;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="delivery_address_id")
    public Integer getDeliveryAddressId() {
        return this.deliveryAddressId;
    }
    
    public void setDeliveryAddressId(Integer deliveryAddressId) {
        this.deliveryAddressId = deliveryAddressId;
    }
    
    @Column(name="value")
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


