package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CreditLine generated by hbm2java
 */
@Entity
@Table(name="Credit_Line"
    ,catalog="corebanking_db"
)
public class CreditLine  implements java.io.Serializable {


     private Integer id;
     private String amount;
     private Integer balanceId;
     private String currency;
     private String included;
     private String type;

    public CreditLine() {
    }

    public CreditLine(String amount, Integer balanceId, String currency, String included, String type) {
       this.amount = amount;
       this.balanceId = balanceId;
       this.currency = currency;
       this.included = included;
       this.type = type;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="amount")
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    
    @Column(name="balance_id")
    public Integer getBalanceId() {
        return this.balanceId;
    }
    
    public void setBalanceId(Integer balanceId) {
        this.balanceId = balanceId;
    }
    
    @Column(name="currency")
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    
    @Column(name="included")
    public String getIncluded() {
        return this.included;
    }
    
    public void setIncluded(String included) {
        this.included = included;
    }
    
    @Column(name="type")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


