package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DeliveryAddress generated by hbm2java
 */
@Entity
@Table(name="DeliveryAddress"
    ,catalog="corebanking_db"
)
public class DeliveryAddress  implements java.io.Serializable {


     private Integer id;
     private String buildingNumber;
     private String country;
     private String postCode;
     private Integer riskId;
     private String streetName;
     private String townName;

    public DeliveryAddress() {
    }

    public DeliveryAddress(String buildingNumber, String country, String postCode, Integer riskId, String streetName, String townName) {
       this.buildingNumber = buildingNumber;
       this.country = country;
       this.postCode = postCode;
       this.riskId = riskId;
       this.streetName = streetName;
       this.townName = townName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="building_number")
    public String getBuildingNumber() {
        return this.buildingNumber;
    }
    
    public void setBuildingNumber(String buildingNumber) {
        this.buildingNumber = buildingNumber;
    }
    
    @Column(name="country")
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="post_code")
    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }
    
    @Column(name="risk_id")
    public Integer getRiskId() {
        return this.riskId;
    }
    
    public void setRiskId(Integer riskId) {
        this.riskId = riskId;
    }
    
    @Column(name="street_name")
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
    
    @Column(name="town_name")
    public String getTownName() {
        return this.townName;
    }
    
    public void setTownName(String townName) {
        this.townName = townName;
    }




}


