package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PaymentInitiationInfo generated by hbm2java
 */
@Entity
@Table(name="PaymentInitiationInfo"
    ,catalog="corebanking_db"
)
public class PaymentInitiationInfo  implements java.io.Serializable {


     private Integer id;
     private String initiationCreditorAccountIdentification;
     private String initiationCreditorAccountName;
     private String initiationCreditorAccountSecondaryIdentification;
     private String initiationDebtorAccountIdentification;
     private String initiationEndToEndIdentification;
     private String initiationInstructedAmount;
     private String initiationRemittanceInformationReference;
     private String initiationRemittanceInformationUnstructured;

    public PaymentInitiationInfo() {
    }

    public PaymentInitiationInfo(String initiationCreditorAccountIdentification, String initiationCreditorAccountName, String initiationCreditorAccountSecondaryIdentification, String initiationDebtorAccountIdentification, String initiationEndToEndIdentification, String initiationInstructedAmount, String initiationRemittanceInformationReference, String initiationRemittanceInformationUnstructured) {
       this.initiationCreditorAccountIdentification = initiationCreditorAccountIdentification;
       this.initiationCreditorAccountName = initiationCreditorAccountName;
       this.initiationCreditorAccountSecondaryIdentification = initiationCreditorAccountSecondaryIdentification;
       this.initiationDebtorAccountIdentification = initiationDebtorAccountIdentification;
       this.initiationEndToEndIdentification = initiationEndToEndIdentification;
       this.initiationInstructedAmount = initiationInstructedAmount;
       this.initiationRemittanceInformationReference = initiationRemittanceInformationReference;
       this.initiationRemittanceInformationUnstructured = initiationRemittanceInformationUnstructured;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="initiation_creditor_account_identification")
    public String getInitiationCreditorAccountIdentification() {
        return this.initiationCreditorAccountIdentification;
    }
    
    public void setInitiationCreditorAccountIdentification(String initiationCreditorAccountIdentification) {
        this.initiationCreditorAccountIdentification = initiationCreditorAccountIdentification;
    }
    
    @Column(name="initiation_creditor_account_name")
    public String getInitiationCreditorAccountName() {
        return this.initiationCreditorAccountName;
    }
    
    public void setInitiationCreditorAccountName(String initiationCreditorAccountName) {
        this.initiationCreditorAccountName = initiationCreditorAccountName;
    }
    
    @Column(name="initiation_creditor_account_secondary_identification")
    public String getInitiationCreditorAccountSecondaryIdentification() {
        return this.initiationCreditorAccountSecondaryIdentification;
    }
    
    public void setInitiationCreditorAccountSecondaryIdentification(String initiationCreditorAccountSecondaryIdentification) {
        this.initiationCreditorAccountSecondaryIdentification = initiationCreditorAccountSecondaryIdentification;
    }
    
    @Column(name="initiation_debtor_account_identification")
    public String getInitiationDebtorAccountIdentification() {
        return this.initiationDebtorAccountIdentification;
    }
    
    public void setInitiationDebtorAccountIdentification(String initiationDebtorAccountIdentification) {
        this.initiationDebtorAccountIdentification = initiationDebtorAccountIdentification;
    }
    
    @Column(name="initiation_end_to_end_identification")
    public String getInitiationEndToEndIdentification() {
        return this.initiationEndToEndIdentification;
    }
    
    public void setInitiationEndToEndIdentification(String initiationEndToEndIdentification) {
        this.initiationEndToEndIdentification = initiationEndToEndIdentification;
    }
    
    @Column(name="initiation_instructed_amount")
    public String getInitiationInstructedAmount() {
        return this.initiationInstructedAmount;
    }
    
    public void setInitiationInstructedAmount(String initiationInstructedAmount) {
        this.initiationInstructedAmount = initiationInstructedAmount;
    }
    
    @Column(name="initiation_remittance_information_reference")
    public String getInitiationRemittanceInformationReference() {
        return this.initiationRemittanceInformationReference;
    }
    
    public void setInitiationRemittanceInformationReference(String initiationRemittanceInformationReference) {
        this.initiationRemittanceInformationReference = initiationRemittanceInformationReference;
    }
    
    @Column(name="initiation_remittance_information_unstructured")
    public String getInitiationRemittanceInformationUnstructured() {
        return this.initiationRemittanceInformationUnstructured;
    }
    
    public void setInitiationRemittanceInformationUnstructured(String initiationRemittanceInformationUnstructured) {
        this.initiationRemittanceInformationUnstructured = initiationRemittanceInformationUnstructured;
    }




}


