package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Risk generated by hbm2java
 */
@Entity
@Table(name="Risk"
    ,catalog="corebanking_db"
)
public class Risk  implements java.io.Serializable {


     private Integer id;
     private Integer initiationId;
     private String merchantCategoryCode;
     private String merchantCustomerIdentification;
     private String paymentContextCode;

    public Risk() {
    }

    public Risk(Integer initiationId, String merchantCategoryCode, String merchantCustomerIdentification, String paymentContextCode) {
       this.initiationId = initiationId;
       this.merchantCategoryCode = merchantCategoryCode;
       this.merchantCustomerIdentification = merchantCustomerIdentification;
       this.paymentContextCode = paymentContextCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="initiation_id")
    public Integer getInitiationId() {
        return this.initiationId;
    }
    
    public void setInitiationId(Integer initiationId) {
        this.initiationId = initiationId;
    }
    
    @Column(name="merchant_category_code")
    public String getMerchantCategoryCode() {
        return this.merchantCategoryCode;
    }
    
    public void setMerchantCategoryCode(String merchantCategoryCode) {
        this.merchantCategoryCode = merchantCategoryCode;
    }
    
    @Column(name="merchant_customer_identification")
    public String getMerchantCustomerIdentification() {
        return this.merchantCustomerIdentification;
    }
    
    public void setMerchantCustomerIdentification(String merchantCustomerIdentification) {
        this.merchantCustomerIdentification = merchantCustomerIdentification;
    }
    
    @Column(name="payment_context_code")
    public String getPaymentContextCode() {
        return this.paymentContextCode;
    }
    
    public void setPaymentContextCode(String paymentContextCode) {
        this.paymentContextCode = paymentContextCode;
    }




}


