package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubAccount generated by hbm2java
 */
@Entity
@Table(name="Sub_Account"
    ,catalog="corebanking_db"
)
public class SubAccount  implements java.io.Serializable {


     private Integer id;
     private Integer accountId;
     private String identification;
     private String name;
     private String schemeName;
     private String secondaryIdentification;

    public SubAccount() {
    }

    public SubAccount(Integer accountId, String identification, String name, String schemeName, String secondaryIdentification) {
       this.accountId = accountId;
       this.identification = identification;
       this.name = name;
       this.schemeName = schemeName;
       this.secondaryIdentification = secondaryIdentification;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="account_id")
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    
    @Column(name="identification")
    public String getIdentification() {
        return this.identification;
    }
    
    public void setIdentification(String identification) {
        this.identification = identification;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="scheme_name")
    public String getSchemeName() {
        return this.schemeName;
    }
    
    public void setSchemeName(String schemeName) {
        this.schemeName = schemeName;
    }
    
    @Column(name="secondary_identification")
    public String getSecondaryIdentification() {
        return this.secondaryIdentification;
    }
    
    public void setSecondaryIdentification(String secondaryIdentification) {
        this.secondaryIdentification = secondaryIdentification;
    }




}


