package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserLoginAccount generated by hbm2java
 */
@Entity
@Table(name="UserLoginAccount"
    ,catalog="corebanking_db"
)
public class UserLoginAccount  implements java.io.Serializable {


     private Integer id;
     private Integer userProfileId;
     private String username;
     private String password;

    public UserLoginAccount() {
    }

    public UserLoginAccount(Integer userProfileId, String username, String password) {
       this.userProfileId = userProfileId;
       this.username = username;
       this.password = password;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="user_profile_id")
    public Integer getUserProfileId() {
        return this.userProfileId;
    }
    
    public void setUserProfileId(Integer userProfileId) {
        this.userProfileId = userProfileId;
    }
    
    @Column(name="username")
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


