package com.virgence.example.entity;
// Generated Jul 12, 2019 1:14:17 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name="user_profile"
    ,catalog="corebanking_db"
)
public class UserProfile  implements java.io.Serializable {


     private Integer id;
     private String accountCode;
     private String accountManager;
     private String accountName;
     private String accountStatus;
     private String accountType;
     private String addressline1;
     private String addressline2;
     private String addressline3;
     private String city;
     private String contactPerson;
     private String country;
     private String createdTimeStamp;
     private String email;
     private String lastActivityTimestamp;
     private String postalCode;
     private String profileId;
     private String state;
     private String updatedTimestamp;

    public UserProfile() {
    }

    public UserProfile(String accountCode, String accountManager, String accountName, String accountStatus, String accountType, String addressline1, String addressline2, String addressline3, String city, String contactPerson, String country, String createdTimeStamp, String email, String lastActivityTimestamp, String postalCode, String profileId, String state, String updatedTimestamp) {
       this.accountCode = accountCode;
       this.accountManager = accountManager;
       this.accountName = accountName;
       this.accountStatus = accountStatus;
       this.accountType = accountType;
       this.addressline1 = addressline1;
       this.addressline2 = addressline2;
       this.addressline3 = addressline3;
       this.city = city;
       this.contactPerson = contactPerson;
       this.country = country;
       this.createdTimeStamp = createdTimeStamp;
       this.email = email;
       this.lastActivityTimestamp = lastActivityTimestamp;
       this.postalCode = postalCode;
       this.profileId = profileId;
       this.state = state;
       this.updatedTimestamp = updatedTimestamp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="account_code")
    public String getAccountCode() {
        return this.accountCode;
    }
    
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }
    
    @Column(name="account_manager")
    public String getAccountManager() {
        return this.accountManager;
    }
    
    public void setAccountManager(String accountManager) {
        this.accountManager = accountManager;
    }
    
    @Column(name="account_name")
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }
    
    @Column(name="account_status")
    public String getAccountStatus() {
        return this.accountStatus;
    }
    
    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }
    
    @Column(name="account_type")
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }
    
    @Column(name="addressline1")
    public String getAddressline1() {
        return this.addressline1;
    }
    
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }
    
    @Column(name="addressline2")
    public String getAddressline2() {
        return this.addressline2;
    }
    
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }
    
    @Column(name="addressline3")
    public String getAddressline3() {
        return this.addressline3;
    }
    
    public void setAddressline3(String addressline3) {
        this.addressline3 = addressline3;
    }
    
    @Column(name="city")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
    @Column(name="contact_person")
    public String getContactPerson() {
        return this.contactPerson;
    }
    
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }
    
    @Column(name="country")
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    @Column(name="created_time_stamp")
    public String getCreatedTimeStamp() {
        return this.createdTimeStamp;
    }
    
    public void setCreatedTimeStamp(String createdTimeStamp) {
        this.createdTimeStamp = createdTimeStamp;
    }
    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="last_activity_timestamp")
    public String getLastActivityTimestamp() {
        return this.lastActivityTimestamp;
    }
    
    public void setLastActivityTimestamp(String lastActivityTimestamp) {
        this.lastActivityTimestamp = lastActivityTimestamp;
    }
    
    @Column(name="postal_code")
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    
    @Column(name="profile_id")
    public String getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(String profileId) {
        this.profileId = profileId;
    }
    
    @Column(name="state")
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    
    @Column(name="updated_timestamp")
    public String getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }
    
    public void setUpdatedTimestamp(String updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }




}


